name: videolibrary
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.1
  flutterfire_ui: ^0.4.3+3
  file_picker: ^5.0.1
  firebase_storage: ^10.3.4
  cloud_firestore: ^3.4.3
  http: ^0.13.5
  video_player: ^2.4.5
  video_box: ^0.16.1
  chewie: ^1.3.4

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

